apiVersion: v1
kind: Secret
metadata:
    name: upstat-secret
    namespace: upstat
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:hR1O29tL,iv:oMriLMug0OU905KVafYmQzFJKSE9Wo8AyeYfHx8Syek=,tag:0aOqeaoH2L2zFhc6HvCQrQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:leRZtO4mRCE=,iv:pRe/LZ4LLcG/aDmDpRRSHtlWS0ZeQSFNI7NjKdLoJlo=,tag:HybthSODRiOPXSxHTRlKIg==,type:str]
    POSTGRES_DSN: ENC[AES256_GCM,data:WxvIKFGTEjLhmYP82uzAR6UlnOjHoO088tehPGmpUI4sV8rYMlcH+qdqpAHWz39kUxMxacSGbRILBLwyCHMTpdE=,iv:89nwa44d7GWyUPt/DZbjmgMuVjj6xEo7sV/8ThikFpE=,tag:gHC2oGK9hFe3m/bed2rflA==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:+9f4ciMW7424hl4F+fU6iczC55+GeEu/1Q35IQ==,iv:A4PIj1lRZqwImGRhQkMWVkgi0jY63wuGLjQin9l9Xsc=,tag:+3j8BEXRDFB3QHAw09zb3g==,type:str]
sops:
    age:
        - recipient: age1svhxh2aql567xg7d0h6wyxmypd36th6s63j70ft8c8w7w56mtp7sm6xjae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ20zK0VPdTZoWlJxNnVD
            eVl3cGtZV29SV0tRbUVnUDBPRzZHNnY0YkNnCm13cWovelRSS2V2Ylozd3FZVjNN
            Snd4M0lvSG9mdTNMVUJzTjFyN0tzQVEKLS0tIDlVdTdMQVhza0lTbGVxL2tzVUhB
            azJZZ3o3TVp5LzN5WklEckdRaFhtaWMKZPXeu5cizv3wmu/oiZGr48JLZlyaHk3p
            msKxkPhreGHseoXh34tVCPwQjqqG/tuAe3IlMqfE3iCAGcT/TWUl4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T15:03:33Z"
    mac: ENC[AES256_GCM,data:KcKaoueqrLdNsMRJFCm1bfXWkVrdzDJUhdVsDJkrYUEcT9QkUPJTA3emBjXoTgk7s+iODq5T8zhxHoHU53FJj74nIjmGfybRzW/p2XSrHSXu/gGiqUTbY/ov4iwEuTyG7f3Zf1y1uQZ4AE7oEOXM7QwlSIv96KerUzj9fO/Z9ss=,iv:5IBmNwrjHmKpc0sAV8rxWaHXd4qXDLmPJE6oY6evSck=,tag:6rvY/hTDEAeqhKPIW/2wRw==,type:str]
    encrypted_regex: ^(data|stringData|secrets|password|token|key)$
    version: 3.11.0
